# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node's name is included in this list
Configuration :
  - Name : alice 
    IP   : 128.237.241.138
    Port : 12344        # This is the incoming port on which MP will listen
                        # May be changed for further communication as usual
  - Name : bob 
    IP   : 128.237.241.138
    Port : 14255
  - Name : charlie
    IP   : 192.168.0.104
    Port : 12998
  - Name : daphnie
    IP   : 192.168.0.104
    Port : 19870

SendRules :
  - Action : drop # Ack message number 4 from bob to alice will not be sent
    Src    : alice
    Dest   : bob
    Kind   : Ack
    Nth    : 3
  - Action : delay # Every Lookup message in the system will be delayed
    Kind   : Lookup
  - Action : duplicate
    Src    : alice
    EveryNth : 5

ReceiveRules :
  - Action : duplicate      # 3rd message from Charlie that anyone 
    Src    : alice        # receives will be duplicated
    Nth    : 3
